### PR TITLE
Create juliana

### PR DESCRIPTION
**Pull request by julianasouza-s**

### CODE REVIEW

**Comment by markliuyuxiang** [comment]
Incorrect JSON format

**Comment by markliuyuxiang** [comment]
Incorrect JSON syntax, please check

**Comment by julianasouza-s** [comment]
Oops, sorry. Just Updated.

Doubt: is there a way to do not force dark mode? (didn't know where to ask this other than here)

**Comment by markliuyuxiang** [comment]
Wrong folder. It should be in the your.notion.dog folder.
Wrong file type. It requires ".json"

**Pull request merged**
